name: LRRcraftBukkit
main: net.darkmorford.lrrcraftbukkit.LRRcraftBukkit
version: 0.1-SNAPSHOT
author: DarkMorford
description: LoadingReadyRun Twitch notifier
commands:
  lrr refresh:
    description: Refresh the current status of the Twitch stream
