name: LRRcraftBukkit
main: net.darkmorford.lrrcraftbukkit.LRRcraftBukkit
version: 0.1-SNAPSHOT
author: DarkMorford
description: LRRcraft Bukkit plugin
commands:
# Miscellaneous commands
  lrrcraftbukkit:
    usage: /lrrcraftbukkit
    aliases: [lcb]
    description: LRRcraft Bukkit plugin
  lrrcraftbukkit map:
    usage: /lrrcraftbukkit map
    aliases: [lcb map]
    description: Link to the DynMap
  lrrcraftbukkit discord:
    usage: /lrrcraftbukkit discord
    aliases: [lcb discord]
    description: Link to the Discord channel
# Economy commands
  money:
    usage: /money
    aliases: [balance]
    description: Shows your current balance
