name: LRRcraftBukkit
main: net.darkmorford.lrrcraftbukkit.LRRcraftBukkit
version: 0.1-SNAPSHOT
author: DarkMorford
description: LRRcraft Bukkit plugin
commands:
  lrrcraftbukkit:
    usage: /lrrcraftbukkit
    aliases: [lcb]
    description: LRRcraft Bukkit plugin
